name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Pipeline de Validação
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check format
        run: bun run format --check

      - name: Test unit
        run: bun run test:unit

      - name: Spin up infrastructure
        run: docker compose up -d

      - name: Wait for services
        run: sleep 45

      - name: Test e2e
        run: bun run test:e2e
        env:
          TEST_KONG_URL: http://localhost:8000
          TEST_KEYCLOAK_TOKEN_URL: http://localhost:8080/realms/crash-game/protocol/openid-connect/token
